const Permission = {
    // user
    CREATE_USER: "CREATE_USER",
    READ_SINGLE_USER: "READ_SINGLE_USER",
    READ_USERS: "READ_USERS",
    UPDATE_USERS: "UPDATE_USERS",
    DELETE_USERS: "DELETE_USERS",
    DISABLE_USERS: "DISABLE_USERS",
    READ_PROFILES: "READ_PROFILES",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    READ_SINGLE_PROFILE: "READ_SINGLE_PROFILE",
    READ_LITE_PROFILE: "READ_LITE_PROFILE",
    UPDATE_USERS_PASSWORD: "UPDATE_USERS_PASSWORD",
    UPDATE_PASSWORD: "UPDATE_PASSWORD",

    // role
    CREATE_ROLE: "CREATE_ROLE",
    UPDATE_ROLE: "UPDATE_ROLE",
    READ_ROLES: "READ_ROLES",
    READ_SINGLE_ROLE: "READ_SINGLE_ROLE",
    DELETE_ROLE: "DELETE_ROLE",

    // static page
    CREATE_STATIC_PAGE: "CREATE_STATIC_PAGE",
    UPDATE_STATIC_PAGE: "UPDATE_STATIC_PAGE",
    READ_STATIC_PAGES: "READ_STATIC_PAGES",
    READ_SINGLE_STATIC_PAGE: "READ_SINGLE_STATIC_PAGE",
    DELETE_STATIC_PAGE: "DELETE_STATIC_PAGE"
};

export default Permission;
